image: gitpod/workspace-full-vnc

tasks:
  - name: SETUP - Download data
    init: |
      cd /workspace
      curl -L "https://gitlab.com/wtsi-grit/rapid-curation/-/archive/main/rapid-curation-main.tar.gz?path=test_data" | tar xzf -
      mv rapid-curation-main-test_data/test_data ./
      rmdir rapid-curation-main-test_data
      gunzip test_data/*.gz

  - name: SETUP - MAMBA ENVIRONMENT
    init: |
      # Download and install Mambaforge
      wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
      bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge
      rm Mambaforge-24.3.0-0-Linux-x86_64.sh

      # Update the PATH to include Mambaforge binaries
      export PATH="/workspace/mambaforge/bin:$PATH"

      # Create the Mamba environment with required packages
      mamba create -n hydrax -c bioconda holoviews bokeh matplotlib ipykernel -y

      # Register the hydrax environment as a Jupyter kernel
      source /workspace/mambaforge/bin/activate hydrax
      python -m ipykernel install --user --name=hydrax --display-name "Hydrax Environment"

      # Sync task completion with Gitpod
      gp sync-done bundle

  - name: SETUP - DOWNLOAD HYDRAX
    init: |
      git clone https://github.com/Amjad-Khalaf/HyraxDotPlot.git
      cd HyraxDotPlot
      python hyraxdotplot.py -h

  - name: MAIN - TERMINAL TO USE
    init: gp sync-await bundle # Wait for previous 'inits' to complete
    command: |
      # Activate the Mamba environment for use in the terminal
      source /workspace/mambaforge/bin/activate hydrax
      echo 'Hello'

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

vscode:
    extensions:
        - ms-toolsai.jupyter
        - ms-python.python

workspaceLocation: "/workspace"
